site_name: Travelport Event-Driven Microservice practices
epo_url: https://github.ibm.com/Travelport-Rail/tvpt-docs/
nav:
  - Home: index.md
  - Fit for purpose: /concepts/fit-for-purpose/
  - Design Patterns:
    - Event Sourcing: /patterns/event-sourcing/
    - CQRS: /patterns/cqrs/
  

theme: 
  name: material
  logo: 'images/cloud.png'
  feature:
    tabs: true
  palette:
      primary: 'blue dark'
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences