site_name: Travelport Event-Driven Microservice practices
repo_url: https://github.ibm.com/Travelport-Rail/tvpt-docs/
nav:
  - Home: index.md
  - EDA Concepts: concepts/terms-and-definitions/
  - Fit for purpose: concepts/fit-for-purpose/
  - Design Patterns:
    - Event Sourcing: patterns/event-sourcing/
    - CQRS: patterns/cqrs/
    - Outbox: patterns/transactional-outbox/
    - SAGA: patterns/saga/
  

theme: 
  name: material
  logo: 'images/cloud.png'
  feature:
    tabs: true
  palette:
      primary: 'blue dark'
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences