site_name: Travelport Event-Driven Microservice practices
repo_url: https://github.com/jbcodeforce/tvpt-docs/
nav:
  - Home: index.md
  - EDA Concepts: concepts/terms-and-definitions/index.md
  - Fit for purpose: concepts/fit-for-purpose/index.md
  - Methodology: methodology
  - Design Patterns:
    - API management: patterns/api_mgt/index.md
    - Event Sourcing: patterns/event-sourcing/index.md
    - CQRS: patterns/cqrs/index.md
    - Outbox: patterns/transactional-outbox/index.md
    - SAGA: patterns/saga/index.md
    - Dead letter queue: patterns/dlq/index.md
  - Technology:
    - CICD for Travelport: patterns/cicd/index.md
    - Kafka Summary: technology/kafka-overview/index.md
    - Producer - Consumer: technology/kafka-producers-consumers/index.md
    - Kafka FAQ: technology/faq/index.md
    - Kafka Konnect: technology/kafka-connect/index.md
    - Spring cloud: technology/spring/index.md

theme: 
  name: material
  logo: 'images/travelportlogo.png'
  feature:
    tabs: true
  palette:
      primary: 'blue dark'
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
